# Generated by Django 5.1.4 on 2025-03-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=36),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='block_number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(db_index=True, max_length=66, unique=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('tx_hash',), name='unique_transaction_hash'),
        ),
    ]
