# Generated by Django 5.1.4 on 2025-03-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_unique_transaction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_transaction',
        ),
    ]
