# Generated by Django 5.1.4 on 2025-03-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_transaction_unique_transaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('sender', 'recipient', 'amount', 'timestamp'), name='unique_transaction'),
        ),
    ]
